centauri:
  mode: 0123456789abcdef                         # Mode to be paired with Centauri
  subMode: 0123456789abcdef                      # SubMode to be paired with Centauri
wars:
  cage-area: 1
  refills: 1
  interval: 60